#include "MOTION_DEFINE.h"

#pragma once

//------------------------------------------------------------------
//                 Device Type Defines.
//------------------------------------------------------------------
// Driver Type E group : Ezi-SERVO Plus-R BLDC Family
#ifndef DEVTYPE_EZI_SERVO_PLUS_R_BLDC_ST
#define	DEVTYPE_EZI_SERVO_PLUS_R_BLDC_ST	40
#define DEVNAME_EZI_SERVO_PLUS_R_BLDC_ST	"Ezi-SERVO Plus-R BLDC F60"
#endif

//------------------------------------------------------------------
//                 Axis Status Flag Defines.
//------------------------------------------------------------------

typedef union
{
	DWORD	dwValue;
	struct
	{
		unsigned	FFLAG_ERRORALL			: 1; // = 0x00000001;
		unsigned	FFLAG_HWPOSILMT			: 1; // = 0x00000002;
		unsigned	FFLAG_HWNEGALMT			: 1; // = 0x00000004;
		unsigned	FFLAG_SWPOGILMT			: 1; // = 0x00000008;
		unsigned	FFLAG_SWNEGALMT			: 1; // = 0x00000010;
		unsigned	FFLAG_RESERVED0			: 1; // = 0x00000020;
		unsigned	FFLAG_ERROVERCURRENT	: 1; // = 0x00000040;
		unsigned	FFLAG_ERROVERSPEED		: 1; // = 0x00000080;
		unsigned	FFLAG_ERRPOSTRACKING	: 1; // = 0x00000100;
		unsigned	FFLAG_ERROVERLOAD		: 1; // = 0x00000200;
		unsigned	FFLAG_ERROVERHEAT		: 1; // = 0x00000400;
		unsigned	FFLAG_ERRBACKEMF		: 1; // = 0x00000800;
		unsigned	FFLAG_ERRMOTORCONNECT	: 1; // = 0x00001000;
		unsigned	FFLAG_ERRENCODERCONNECT	: 1; // = 0x00002000;
		unsigned	FFLAG_ERRMOTORPOWER		: 1; // = 0x00004000;
		unsigned	FFLAG_ERRINPOSITION		: 1; // = 0x00008000;
		unsigned	FFLAG_EMGSTOP			: 1; // = 0x00010000;
		unsigned	FFLAG_SLOWSTOP			: 1; // = 0x00020000;
		unsigned	FFLAG_ORIGINRETURNING	: 1; // = 0x00040000;
		unsigned	FFLAG_INPOSITION		: 1; // = 0x00080000;
		unsigned	FFLAG_SERVOON			: 1; // = 0x00100000;
		unsigned	FFLAG_ALARMRESET		: 1; // = 0x00200000;
		unsigned	FFLAG_PTSTOPPED			: 1; // = 0x00400000;
		unsigned	FFLAG_ORIGINSENSOR		: 1; // = 0x00800000;
		unsigned	FFLAG_ZPULSE			: 1; // = 0x01000000;
		unsigned	FFLAG_ORIGINRETOK		: 1; // = 0x02000000;
		unsigned	FFLAG_MOTIONDIR			: 1; // = 0x04000000;
		unsigned	FFLAG_MOTIONING			: 1; // = 0x08000000;
		unsigned	FFLAG_MOTIONPAUSE		: 1; // = 0x10000000;
		unsigned	FFLAG_MOTIONACCEL		: 1; // = 0x20000000;
		unsigned	FFLAG_MOTIONDECEL		: 1; // = 0x40000000;
		unsigned	FFLAG_MOTIONCONST		: 1; // = 0x80000000;
	};
} EZISERVO_BLDC_AXISSTATUS;

//------------------------------------------------------------------
//                 Input/Output Defines.
//------------------------------------------------------------------

// Input Bit-mask list.
#define	SERVO_BLDC_IN_BITMASK_LIMITP		(0x00000001)
#define	SERVO_BLDC_IN_BITMASK_LIMITN		(0x00000002)
#define	SERVO_BLDC_IN_BITMASK_ORIGIN		(0x00000004)
#define	SERVO_BLDC_IN_BITMASK_CLEARPOSITION	(0x00000008)
#define	SERVO_BLDC_IN_BITMASK_PTA0			(0x00000010)
#define	SERVO_BLDC_IN_BITMASK_PTA1			(0x00000020)
#define	SERVO_BLDC_IN_BITMASK_PTA2			(0x00000040)
#define	SERVO_BLDC_IN_BITMASK_PTA3			(0x00000080)
#define	SERVO_BLDC_IN_BITMASK_PTA4			(0x00000100)
#define	SERVO_BLDC_IN_BITMASK_PTA5			(0x00000200)
#define	SERVO_BLDC_IN_BITMASK_PTA6			(0x00000400)
#define	SERVO_BLDC_IN_BITMASK_PTA7			(0x00000800)
#define	SERVO_BLDC_IN_BITMASK_PTSTART		(0x00001000)
#define	SERVO_BLDC_IN_BITMASK_STOP			(0x00002000)
#define	SERVO_BLDC_IN_BITMASK_PJOG			(0x00004000)
#define	SERVO_BLDC_IN_BITMASK_NJOG			(0x00008000)
#define	SERVO_BLDC_IN_BITMASK_ALARMRESET	(0x00010000)
#define	SERVO_BLDC_IN_BITMASK_SERVOON		(0x00020000)
#define	SERVO_BLDC_IN_BITMASK_PAUSE			(0x00040000)
#define	SERVO_BLDC_IN_BITMASK_ORIGINSEARCH	(0x00080000)
#define	SERVO_BLDC_IN_BITMASK_TEACHING		(0x00100000)
#define	SERVO_BLDC_IN_BITMASK_ESTOP			(0x00200000)
#define	SERVO_BLDC_IN_BITMASK_JPTIN0		(0x00400000)
#define	SERVO_BLDC_IN_BITMASK_JPTIN1		(0x00800000)
#define	SERVO_BLDC_IN_BITMASK_JPTIN2		(0x01000000)
#define	SERVO_BLDC_IN_BITMASK_JPTSTART		(0x02000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN0		(0x04000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN1		(0x08000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN2		(0x10000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN3		(0x20000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN4		(0x40000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN5		(0x80000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN6		(0x100000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN7		(0x200000000)
#define	SERVO_BLDC_IN_BITMASK_USERIN8		(0x400000000)

// Output Bit-mask list.
#define	SERVO_BLDC_OUT_BITMASK_COMPAREOUT	(0x00000001)
#define	SERVO_BLDC_OUT_BITMASK_INPOSITION	(0x00000002)
#define	SERVO_BLDC_OUT_BITMASK_ALARM		(0x00000004)
#define	SERVO_BLDC_OUT_BITMASK_MOVING		(0x00000008)
#define	SERVO_BLDC_OUT_BITMASK_ACCDEC		(0x00000010)
#define	SERVO_BLDC_OUT_BITMASK_PTACK		(0x00000020)
#define	SERVO_BLDC_OUT_BITMASK_PTEND		(0x00000040)
#define	SERVO_BLDC_OUT_BITMASK_ALARMBLINK	(0x00000080)
#define	SERVO_BLDC_OUT_BITMASK_ORGSEARCHOK	(0x00000100)
#define	SERVO_BLDC_OUT_BITMASK_SERVOREADY	(0x00000200)
//#define	SERVO_BLDC_OUT_BITMASK_RESERVED	(0x00000400)
#define	SERVO_BLDC_OUT_BITMASK_BRAKE		(0x00000800)
#define	SERVO_BLDC_OUT_BITMASK_PTOUT0		(0x00001000)
#define	SERVO_BLDC_OUT_BITMASK_PTOUT1		(0x00002000)
#define	SERVO_BLDC_OUT_BITMASK_PTOUT2		(0x00004000)
#define	SERVO_BLDC_OUT_BITMASK_PTOUT3		(0x00008000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT0		(0x00010000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT1		(0x00020000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT2		(0x00040000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT3		(0x00080000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT4		(0x00100000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT5		(0x00200000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT6		(0x00400000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT7		(0x00800000)
#define	SERVO_BLDC_OUT_BITMASK_USEROUT8		(0x01000000)

typedef union
{
	ULONGLONG	uValue;
	struct
	{
		unsigned BIT_LIMITP		: 1;
		unsigned BIT_LIMITN		: 1;
		unsigned BIT_ORIGIN		: 1;
		
		unsigned BIT_CLEARPOSITION	: 1;
		unsigned BIT_PTA0			: 1;
		unsigned BIT_PTA1			: 1;
		unsigned BIT_PTA2			: 1;
		unsigned BIT_PTA3			: 1;
		unsigned BIT_PTA4			: 1;
		unsigned BIT_PTA5			: 1;
		unsigned BIT_PTA6			: 1;
		unsigned BIT_PTA7			: 1;
		unsigned BIT_PTSTART		: 1;
		unsigned BIT_STOP			: 1;
		unsigned BIT_PJOG			: 1;
		unsigned BIT_NJOG			: 1;
		unsigned BIT_ALARMRESET		: 1;
		unsigned BIT_SERVOON		: 1;
		unsigned BIT_PAUSE			: 1;
		unsigned BIT_ORIGINSEARCH	: 1;
		unsigned BIT_TEACHING		: 1;
		unsigned BIT_ESTOP			: 1;
		unsigned BIT_JPTIN0			: 1;
		unsigned BIT_JPTIN1			: 1;
		unsigned BIT_JPTIN2			: 1;
		unsigned BIT_JPTSTART		: 1;
		unsigned BIT_USERIN0		: 1;
		unsigned BIT_USERIN1		: 1;
		unsigned BIT_USERIN2		: 1;
		unsigned BIT_USERIN3		: 1;
		unsigned BIT_USERIN4		: 1;
		unsigned BIT_USERIN5		: 1;
		unsigned BIT_USERIN6		: 1;
		unsigned BIT_USERIN7		: 1;
		unsigned BIT_USERIN8		: 1;
	};
} EZISERVO_BLDC_INPUT;

typedef union
{
	DWORD dwValue;
	struct
	{
		unsigned BIT_COMPAREOUT		: 1;
		unsigned BIT_INPOSITION		: 1;
		unsigned BIT_ALARM			: 1;
		unsigned BIT_MOVING			: 1;
		unsigned BIT_ACCDEC			: 1;
		unsigned BIT_PTACK			: 1;
		unsigned BIT_PTEND			: 1;
		unsigned BIT_ALARMBLINK		: 1;
		unsigned BIT_ORGSEARCHOK	: 1;
		unsigned BIT_SERVOREADY		: 1;
		unsigned BIT_RESERVED0		: 1;
		unsigned BIT_BRAKE			: 1;
		unsigned BIT_PTOUT0			: 1;
		unsigned BIT_PTOUT1			: 1;
		unsigned BIT_PTOUT2			: 1;
		unsigned BIT_PTOUT3			: 1;
		unsigned BIT_USEROUT0		: 1;
		unsigned BIT_USEROUT1		: 1;
		unsigned BIT_USEROUT2		: 1;
		unsigned BIT_USEROUT3		: 1;
		unsigned BIT_USEROUT4		: 1;
		unsigned BIT_USEROUT5		: 1;
		unsigned BIT_USEROUT6		: 1;
		unsigned BIT_USEROUT7		: 1;
		unsigned BIT_USEROUT8		: 1;
	};

} EZISERVO_BLDC_OUTPUT;

//------------------------------------------------------------------
//                 Input/Output Assigning Defines.
//------------------------------------------------------------------
typedef enum
{
	SERVO_BLDC_IN_PREASSIGN_LIMITP = 1,
	SERVO_BLDC_IN_PREASSIGN_LIMITN,
	SERVO_BLDC_IN_PREASSIGN_ORIGIN,

	SERVO_BLDC_IN_LOGIC_CLEARPOSITION,
	SERVO_BLDC_IN_LOGIC_PTA0,
	SERVO_BLDC_IN_LOGIC_PTA1,
	SERVO_BLDC_IN_LOGIC_PTA2,
	SERVO_BLDC_IN_LOGIC_PTA3,
	SERVO_BLDC_IN_LOGIC_PTA4,
	SERVO_BLDC_IN_LOGIC_PTA5,
	SERVO_BLDC_IN_LOGIC_PTA6,
	SERVO_BLDC_IN_LOGIC_PTA7,
	SERVO_BLDC_IN_LOGIC_PTSTART,
	SERVO_BLDC_IN_LOGIC_STOP,
	SERVO_BLDC_IN_LOGIC_PJOG,
	SERVO_BLDC_IN_LOGIC_NJOG,
	SERVO_BLDC_IN_LOGIC_ALARMRESET,
	SERVO_BLDC_IN_LOGIC_SERVOON,
	SERVO_BLDC_IN_LOGIC_PAUSE,
	SERVO_BLDC_IN_LOGIC_ORIGINSEARCH,
	SERVO_BLDC_IN_LOGIC_TEACHING,
	SERVO_BLDC_IN_LOGIC_ESTOP,
	SERVO_BLDC_IN_LOGIC_JPTIN0,
	SERVO_BLDC_IN_LOGIC_JPTIN1,
	SERVO_BLDC_IN_LOGIC_JPTIN2,
	SERVO_BLDC_IN_LOGIC_JPTSTART,
	SERVO_BLDC_IN_LOGIC_USERIN0,
	SERVO_BLDC_IN_LOGIC_USERIN1,
	SERVO_BLDC_IN_LOGIC_USERIN2,
	SERVO_BLDC_IN_LOGIC_USERIN3,
	SERVO_BLDC_IN_LOGIC_USERIN4,
	SERVO_BLDC_IN_LOGIC_USERIN5,
	SERVO_BLDC_IN_LOGIC_USERIN6,
	SERVO_BLDC_IN_LOGIC_USERIN7,
	SERVO_BLDC_IN_LOGIC_USERIN8,

	MAX_SERVO_BLDC_IN_LOGIC
} EZISERVO_BLDC_INLOGIC;

typedef enum
{
	SERVO_BLDC_OUT_PREASSIGN_COMPAREOUT = 1,

	SERVO_BLDC_OUT_LOGIC_INPOSITION,
	SERVO_BLDC_OUT_LOGIC_ALARM,
	SERVO_BLDC_OUT_LOGIC_MOVING,
	SERVO_BLDC_OUT_LOGIC_ACCDEC,
	SERVO_BLDC_OUT_LOGIC_PTACK,
	SERVO_BLDC_OUT_LOGIC_PTEND,
	SERVO_BLDC_OUT_LOGIC_ALARMBLINK,
	SERVO_BLDC_OUT_LOGIC_ORGSEARCHOK,
	SERVO_BLDC_OUT_LOGIC_SERVOREADY,
	SERVO_BLDC_OUT_LOGIC_RESERVED0,
	SERVO_BLDC_OUT_LOGIC_BRAKE,
	SERVO_BLDC_OUT_LOGIC_PTOUT0,
	SERVO_BLDC_OUT_LOGIC_PTOUT1,
	SERVO_BLDC_OUT_LOGIC_PTOUT2,
	SERVO_BLDC_OUT_LOGIC_PTOUT3,
	SERVO_BLDC_OUT_LOGIC_USEROUT0,
	SERVO_BLDC_OUT_LOGIC_USEROUT1,
	SERVO_BLDC_OUT_LOGIC_USEROUT2,
	SERVO_BLDC_OUT_LOGIC_USEROUT3,
	SERVO_BLDC_OUT_LOGIC_USEROUT4,
	SERVO_BLDC_OUT_LOGIC_USEROUT5,
	SERVO_BLDC_OUT_LOGIC_USEROUT6,
	SERVO_BLDC_OUT_LOGIC_USEROUT7,
	SERVO_BLDC_OUT_LOGIC_USEROUT8,

	MAX_SERVO_BLDC_OUT_LOGIC
} EZISERVO_BLDC_OUTLOGIC;

#define	IN_LOGIC_CNT		(MAX_SERVO_BLDC_IN_LOGIC - 1)
#define	MAX_PREASSIGNED_IN	(SERVO_BLDC_IN_PREASSIGN_ORIGIN)

#define	OUT_LOGIC_CNT		(MAX_SERVO_BLDC_OUT_LOGIC - 1)
#define	MAX_PREASSIGNED_OUT (SERVO_BLDC_OUT_PREASSIGN_COMPAREOUT)

static const LPCSTR LOGICLIST_EZISERVO_BLDC_INPUT[IN_LOGIC_CNT] = 
{
	"Limit +",
	"Limit -",
	"Origin",
	"Clear Pos",
	"PT A0",
	"PT A1",
	"PT A2",
	"PT A3",
	"PT A4",
	"PT A5",
	"PT A6",
	"PT A7",
	"PT Start",
	"Stop",
	"Jog +",
	"Jog -",
	"Alarm Reset",
	"Servo On",
	"Pause",
	"Origin Search",
	"Teaching",
	"E-Stop",
	"JPT IN 0",
	"JPT IN 1",
	"JPT IN 2",
	"JPT Start",
	"User IN 0",
	"User IN 1",
	"User IN 2",
	"User IN 3",
	"User IN 4",
	"User IN 5",
	"User IN 6",
	"User IN 7",
	"User IN 8"
};

static const LPCSTR LOGICLIST_EZISERVO_BLDC_OUTPUT[OUT_LOGIC_CNT] = 
{
	"Reserved",
	"Inposition",
	"Alarm",
	"Moving",
	"Acc/Dec",
	"PT ACK",
	"PT End",
	"AlarmBlink",
	"Org Search Ok",
	"Servo Ready",
	"Reserved",
	"Brake",
	"PT OUT 0",
	"PT OUT 1",
	"PT OUT 2",
	"PT OUT 3",
	"User OUT 0",
	"User OUT 1",
	"User OUT 2",
	"User OUT 3",
	"User OUT 4",
	"User OUT 5",
	"User OUT 6",
	"User OUT 7",
	"User OUT 8"
};

//------------------------------------------------------------------
//                 Parameters Defines.
//------------------------------------------------------------------

typedef enum
{
	SERVO_BLDC_AXISMAXSPEED = 0,
	SERVO_BLDC_AXISSTARTSPEED,
	SERVO_BLDC_AXISACCTIME,
	SERVO_BLDC_AXISDECTIME,
	
	SERVO_BLDC_SPEEDOVERRIDE,
	SERVO_BLDC_JOGHIGHSPEED,
	SERVO_BLDC_JOGLOWSPEED,
	SERVO_BLDC_JOGACCDECTIME,
	
	SERVO_BLDC_SERVOALARMLOGIC,
	SERVO_BLDC_SERVOONLOGIC,
	SERVO_BLDC_SERVORESETLOGIC,
	
	SERVO_BLDC_SWLMTPLUSVALUE,
	SERVO_BLDC_SWLMTMINUSVALUE,
	SERVO_BLDC_SOFTLMTSTOPMETHOD,
	SERVO_BLDC_HARDLMTSTOPMETHOD,
	SERVO_BLDC_LIMITSENSORLOGIC,

	SERVO_BLDC_ORGSPEED,
	SERVO_BLDC_ORGSEARCHSPEED,
	SERVO_BLDC_ORGACCDECTIME,
	SERVO_BLDC_ORGMETHOD,
	SERVO_BLDC_ORGDIR,
	SERVO_BLDC_ORGOFFSET,
	SERVO_BLDC_ORGPOSITIONSET,
	SERVO_BLDC_ORGSENSORLOGIC,

	SERVO_BLDC_POSTRACKINGLIMIT,
	SERVO_BLDC_MOTIONDIR,

	SERVO_BLDC_LIMITSENSORDIR,
	SERVO_BLDC_ORGTORQUERATIO,

	SERVO_BLDC_MOTORLEAD,
	SERVO_BLDC_GEARRATIO,

	SERVO_BLDC_POSERROVERFLOWLIMIT,

	MAX_SERVO_BLDC_PARAM

} FM_EZISERVO_BLDC_PARAM;

//------------------------------------------------------------------
//                 BLDC Parameters Defines.
//------------------------------------------------------------------

// Category List
typedef enum
{
	BLDC_CATEGORY_DRIVER = 1,
	BLDC_CATEGORY_MOTORENCODER,
	BLDC_CATEGORY_POSITIONCONTROL,
	BLDC_CATEGORY_SPEEDCONTROL,
	BLDC_CATEGORY_CURRENTCONTROL,
	BLDC_CATEGORY_TORQUE,
	BLDC_CATEGORY_ALARMLEVEL,

	BLDC_CATEGORY_LAST
} FM_BLDC_CATEGORY;

static const int MAX_BLDC_CATEGORY = (BLDC_CATEGORY_LAST - 1);

// BLDC_CATEGORY_DRIVER
static const DWORD BLDC_INPOSITION_ACTIVE_LEVEL	= 11;
static const DWORD BLDC_TEMPERATURE				= 17;

// BLDC_CATEGORY_MOTORENCODER
static const DWORD BLDC_MOTORNUMBER				= 1;
static const DWORD BLDC_RATED_CURRENT			= 4;
static const DWORD BLDC_MAX_PEAK_CURRENT		= 5;
static const DWORD BLDC_PEAK_CURRENT_ALARM_TIMEOUT	= 6;
static const DWORD BLDC_TORQUE_CONSTANT			= 7;
static const DWORD BLDC_ROTOR_INERTIA			= 8;
static const DWORD BLDC_RATED_SPEED				= 9;
static const DWORD BLDC_LINETOLINE_RESISTANCE	= 10;
static const DWORD BLDC_LINETOLINE_INDUCTANCE	= 11;
static const DWORD BLDC_ENCODER_RESOLUTION		= 14;
static const DWORD BLDC_MOTOR_POLE_PAIRS		= 15;
static const DWORD BLDC_ENCODER_POLARITY		= 16;
static const DWORD BLDC_ROTOR_ZERO_POS_ESTIM_EN	= 17;
static const DWORD BLDC_RL_ESTIMATE_EN			= 18;

// BLDC_CATEGORY_POSITIONCONTROL
static const DWORD BLDC_POSITION_PROPORTIONAL_GAIN1		= 1;
static const DWORD BLDC_POSITION_PROPORTIONAL_GAIN2		= 2;
static const DWORD BLDC_POSITION_PROPORTIONAL_GAIN_SWITCHLEVEL		= 3;
static const DWORD BLDC_POSITION_PHASE_CORRECTION_LOW_FREQUENCY		= 4;
static const DWORD BLDC_POSITION_PHASE_CORRECTION_HIGH_FREQUENCY	= 5;
static const DWORD BLDC_POSITION_FEEDFORWARD_GAIN		= 6;
static const DWORD BLDC_POSITION_FF_FILTER_BANDWIDTH	= 7;
static const DWORD BLDC_INPOSITION_RAGNE				= 8;
static const DWORD BLDC_INPOSITION_MODE					= 9;
static const DWORD BLDC_ELECTORNIC_GEAR_NUMERATOR		= 10;
static const DWORD BLDC_ELECTORNIC_GEAR_DENUMERATOR		= 11;
static const DWORD BLDC_REFERENCE_POSITION_SMOOTHING_FILTER_TIME_CONSTANT	= 12;

// BLDC_CATEGORY_SPEEDCONTROL
static const DWORD BLDC_SPEED_PROPORTIONAL_GAIN1			= 1;
static const DWORD BLDC_SPEED_PROPORTIONAL_GAIN2			= 2;
static const DWORD BLDC_SPEED_PROPORTIONAL_GAIN_SWITCHLEVEL	= 3;
static const DWORD BLDC_SPEED_INTEGRAL_GAIN					= 4;
static const DWORD BLDC_INERTIA_ROTOR_LOAD					= 5;
static const DWORD BLDC_INERTIA_ESTIMATE_ENABLE				= 6;
static const DWORD BLDC_VIBRATION_NOTCH_FILTER1_FREQUENCY	= 7;
static const DWORD BLDC_VIBRATION_NOTCH_FILTER1_DEPTH		= 8;
static const DWORD BLDC_VIBRATION_NOTCH_FILTER1_Q_FACTOR	= 9;
static const DWORD BLDC_NOTCH_FILTER1_ENABLE_AUTOTUNING_ENABLE	= 10;
static const DWORD BLDC_VIBRATION_NOTCH_FILTER2_FREQUENCY	= 11;
static const DWORD BLDC_VIBRATION_NOTCH_FILTER2_DEPTH		= 12;
static const DWORD BLDC_VIBRATION_NOTCH_FILTER2_Q_FACTOR	= 13;
static const DWORD BLDC_NOTCH_FILTER2_ENABLE				= 14;
static const DWORD BLDC_AT_SPEED_SPEED_ARRIVAL				= 15;
static const DWORD BLDC_ZERO_SPEED							= 16;

// BLDC_CATEGORY_CURRENTCONTROL
static const DWORD BLDC_REFERENCE_CURRENT_FILTER_BANDWIDTH	= 1;
static const DWORD BLDC_CURRENT_CONTROL_BANDWIDTH			= 2;

// BLDC_CATEGORY_TORQUE
static const DWORD BLDC_TORQUE_MAX							= 1;
static const DWORD BLDC_MAX_SPEED_IN_TORQUE_MODE			= 2;
static const DWORD BLDC_TORQUE_MODE_ON						= 3;

// BLDC_CATEGORY_ALARMLEVEL
static const DWORD BLDC_OVERCURRENT_ALARM_LEVEL				= 1;
static const DWORD BLDC_OVERSPEED_ALARM_LEVEL				= 2;

