#if !defined(AFX_BTNENH_H__6E214D69_FDC2_40CF_92B9_C53617DAC5C5__INCLUDED_)
#define AFX_BTNENH_H__6E214D69_FDC2_40CF_92B9_C53617DAC5C5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CSurfaceColor;
class CTextDescriptor;
class CTexture;
class CCellsManager;

/////////////////////////////////////////////////////////////////////////////
// CBtnEnh wrapper class

class CBtnEnh : public CWnd
{
protected:
	DECLARE_DYNCREATE(CBtnEnh)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x40b5ce81, 0xc5a8, 0x11d2, { 0x81, 0x83, 0x0, 0x0, 0x24, 0x40, 0xdf, 0xd8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	long GetShape();
	void SetShape(long);
	long GetSlant();
	void SetSlant(long);
	long GetSurface();
	void SetSurface(long);
	unsigned long GetPictureTranspColor();
	void SetPictureTranspColor(unsigned long);
	CString GetSoundDown();
	void SetSoundDown(LPCTSTR);
	CString GetSoundUp();
	void SetSoundUp(LPCTSTR);
	CString GetCursor();
	void SetCursor(LPCTSTR);
	CString GetSoundMouseOver();
	void SetSoundMouseOver(LPCTSTR);
	CString GetSoundMouseOut();
	void SetSoundMouseOut(LPCTSTR);
	COleFont GetFontTextLT();
	void SetFontTextLT(LPDISPATCH);
	COleFont GetFontTextCT();
	void SetFontTextCT(LPDISPATCH);
	COleFont GetFontTextRT();
	void SetFontTextRT(LPDISPATCH);
	COleFont GetFontTextLM();
	void SetFontTextLM(LPDISPATCH);
	COleFont GetFontTextRM();
	void SetFontTextRM(LPDISPATCH);
	COleFont GetFontTextLB();
	void SetFontTextLB(LPDISPATCH);
	COleFont GetFontTextCB();
	void SetFontTextCB(LPDISPATCH);
	COleFont GetFontTextRB();
	void SetFontTextRB(LPDISPATCH);
	CString GetPicture();
	void SetPicture(LPCTSTR);
	CString GetPicturePressed();
	void SetPicturePressed(LPCTSTR);
	CString GetPictureMouseOver();
	void SetPictureMouseOver(LPCTSTR);
	CString GetPictureCustom();
	void SetPictureCustom(LPCTSTR);
	long GetPicturePosition();
	void SetPicturePosition(long);
	short GetPictureXOffset();
	void SetPictureXOffset(short);
	short GetPictureYOffset();
	void SetPictureYOffset(short);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	long GetPictureTranspMode();
	void SetPictureTranspMode(long);
	unsigned long GetBackColorContainer();
	void SetBackColorContainer(unsigned long);
	BOOL GetMovePictureOnPress();
	void SetMovePictureOnPress(BOOL);
	short GetButtonRaiseFactor();
	void SetButtonRaiseFactor(short);
	unsigned long GetHighlightColor();
	void SetHighlightColor(unsigned long);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long);
	BOOL GetButtonCustomFitPicture();
	void SetButtonCustomFitPicture(BOOL);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	COleFont GetFontTextCaption();
	void SetFontTextCaption(LPDISPATCH);
	CString GetHyperlink();
	void SetHyperlink(LPCTSTR);
	BOOL GetEnableInternetLoadAtDT();
	void SetEnableInternetLoadAtDT(BOOL);
	long GetSmoothEdges();
	void SetSmoothEdges(long);
	CString GetTagEx();
	void SetTagEx(LPCTSTR);
	BOOL GetPictureKeepRatio();
	void SetPictureKeepRatio(BOOL);
	long GetFocusMode();
	void SetFocusMode(long);
	long GetSpecialEffect();
	void SetSpecialEffect(long);
	short GetCaptionWordWrapPerc();
	void SetCaptionWordWrapPerc(short);
	short GetOptimization();
	void SetOptimization(short);
	BOOL GetClickable();
	void SetClickable(BOOL);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	BOOL GetIgnoreSpaceBar();
	void SetIgnoreSpaceBar(BOOL);
	long GetSpecialEffectFactor();
	void SetSpecialEffectFactor(long);
	unsigned long GetForeColorDisabled();
	void SetForeColorDisabled(unsigned long);
	unsigned long GetBackColorDisabled();
	void SetBackColorDisabled(unsigned long);
	unsigned long GetBackColorMouseOver();
	void SetBackColorMouseOver(unsigned long);
	unsigned long GetBackColorFocus();
	void SetBackColorFocus(unsigned long);
	unsigned long GetBackColorInterior();
	void SetBackColorInterior(unsigned long);
	unsigned long GetForeColorMouseOver();
	void SetForeColorMouseOver(unsigned long);
	long GetFlatPillowFactor();
	void SetFlatPillowFactor(long);
	long GetShadowMode();
	void SetShadowMode(long);
	long GetStyle();
	void SetStyle(long);
	CString GetPictureDisabled();
	void SetPictureDisabled(LPCTSTR);
	unsigned long GetForeColorPressed();
	void SetForeColorPressed(unsigned long);
	unsigned long GetBackColorPressed();
	void SetBackColorPressed(unsigned long);
	short GetValue();
	void SetValue(short);
	long GetOrientation();
	void SetOrientation(long);
	CSurfaceColor GetColorSurfaceNormal();
	void SetColorSurfaceNormal(LPDISPATCH);
	CSurfaceColor GetColorSurfaceMO();
	void SetColorSurfaceMO(LPDISPATCH);
	CSurfaceColor GetColorSurfaceInternal();
	void SetColorSurfaceInternal(LPDISPATCH);
	CSurfaceColor GetColorSurfaceFocus();
	void SetColorSurfaceFocus(LPDISPATCH);
	CSurfaceColor GetColorSurfaceDisabled();
	void SetColorSurfaceDisabled(LPDISPATCH);
	CSurfaceColor GetColorSurfacePressed();
	void SetColorSurfacePressed(LPDISPATCH);
	CTextDescriptor GetTextDescrCaption();
	void SetTextDescrCaption(LPDISPATCH);
	CTextDescriptor GetTextDescrLT();
	void SetTextDescrLT(LPDISPATCH);
	CTextDescriptor GetTextDescrCT();
	void SetTextDescrCT(LPDISPATCH);
	CTextDescriptor GetTextDescrRT();
	void SetTextDescrRT(LPDISPATCH);
	CTextDescriptor GetTextDescrLM();
	void SetTextDescrLM(LPDISPATCH);
	CTextDescriptor GetTextDescrRM();
	void SetTextDescrRM(LPDISPATCH);
	CTextDescriptor GetTextDescrLB();
	void SetTextDescrLB(LPDISPATCH);
	CTextDescriptor GetTextDescrCB();
	void SetTextDescrCB(LPDISPATCH);
	CTextDescriptor GetTextDescrRB();
	void SetTextDescrRB(LPDISPATCH);
	CTexture GetTextureSurface();
	void SetTextureSurface(LPDISPATCH);
	long GetFrameEffect();
	void SetFrameEffect(long);
	BOOL GetOptionGroupDelimiter();
	void SetOptionGroupDelimiter(BOOL);
	BOOL GetPictureVisible();
	void SetPictureVisible(BOOL);
	long GetTextCaptionAlignment();
	void SetTextCaptionAlignment(long);
	short GetSpotlightOffsetX();
	void SetSpotlightOffsetX(short);
	short GetSpotlightOffsetY();
	void SetSpotlightOffsetY(short);
	short GetSpotlightResizeWidth();
	void SetSpotlightResizeWidth(short);
	short GetSpotlightResizeHeight();
	void SetSpotlightResizeHeight(short);
	short GetCornerFactor();
	void SetCornerFactor(short);
	BOOL GetUseAntialias();
	void SetUseAntialias(BOOL);
	CCellsManager GetCellsManager();
	void SetCellsManager(LPDISPATCH);
	BOOL GetHollowFrame();
	void SetHollowFrame(BOOL);
	long GetLightDirection();
	void SetLightDirection(long);
	BOOL GetSpotlightVisible();
	void SetSpotlightVisible(BOOL);
	unsigned long GetSpotlightColor();
	void SetSpotlightColor(unsigned long);
	short GetPictureTranspFactor();
	void SetPictureTranspFactor(short);
	short GetShapeHeadFactor();
	void SetShapeHeadFactor(short);
	short GetShapeLineFactor();
	void SetShapeLineFactor(short);
	short GetSurfaceTransparentFactor();
	void SetSurfaceTransparentFactor(short);
	BOOL GetRectHardEdges();
	void SetRectHardEdges(BOOL);
	BOOL GetSwapEffectsColors();
	void SetSwapEffectsColors(BOOL);
	long GetSurfaceTransparentZone();
	void SetSurfaceTransparentZone(long);
	unsigned long GetVistaColorGlossyEffectUpper();
	void SetVistaColorGlossyEffectUpper(unsigned long);
	short GetVistaOpacityGlossyEffectUpper();
	void SetVistaOpacityGlossyEffectUpper(short);
	unsigned long GetVistaColorGlossyEffectLower();
	void SetVistaColorGlossyEffectLower(unsigned long);
	short GetVistaOpacityGlossyEffectLower();
	void SetVistaOpacityGlossyEffectLower(short);
	unsigned long GetVistaColorOuterBorder();
	void SetVistaColorOuterBorder(unsigned long);
	unsigned long GetVistaColorInnerBorder();
	void SetVistaColorInnerBorder(unsigned long);
	unsigned long GetVistaColorInnerBorderPressed();
	void SetVistaColorInnerBorderPressed(unsigned long);
	unsigned long GetVistaColorMiddleBorder();
	void SetVistaColorMiddleBorder(unsigned long);
	unsigned long GetVistaColorGlossyEmphUpper();
	void SetVistaColorGlossyEmphUpper(unsigned long);
	short GetVistaOpacityGlossyEmphUpper();
	void SetVistaOpacityGlossyEmphUpper(short);
	unsigned long GetVistaColorGlossyEmphLower();
	void SetVistaColorGlossyEmphLower(unsigned long);
	short GetVistaOpacityGlossyEmphLower();
	void SetVistaOpacityGlossyEmphLower(short);
	unsigned long GetVistaColorGlossyEmphUpperPressed();
	void SetVistaColorGlossyEmphUpperPressed(unsigned long);
	short GetVistaOpacityGlossyEmphUpperPressed();
	void SetVistaOpacityGlossyEmphUpperPressed(short);
	unsigned long GetVistaColorGlossyEmphLowerPressed();
	void SetVistaColorGlossyEmphLowerPressed(unsigned long);
	short GetVistaOpacityGlossyEmphLowerPressed();
	void SetVistaOpacityGlossyEmphLowerPressed(short);
	unsigned long GetVistaColorGlowBack();
	void SetVistaColorGlowBack(unsigned long);
	unsigned long GetVistaColorGlow();
	void SetVistaColorGlow(unsigned long);
	unsigned long GetVistaColorGlowChecked();
	void SetVistaColorGlowChecked(unsigned long);
	unsigned long GetVistaColorGlowCheckedMouseOver();
	void SetVistaColorGlowCheckedMouseOver(unsigned long);
	unsigned long GetVistaColorBackgroundChecked();
	void SetVistaColorBackgroundChecked(unsigned long);
	unsigned long GetVistaColorBackgroundCheckedMouseOver();
	void SetVistaColorBackgroundCheckedMouseOver(unsigned long);
	long GetVistaLook();
	void SetVistaLook(long);
	long GetVistaGlossyShape();
	void SetVistaGlossyShape(long);
	short GetVistaGlossySmoothFactor();
	void SetVistaGlossySmoothFactor(short);
	long GetSpotlightType();
	void SetSpotlightType(long);
	BOOL GetPictureReflectivityEnabled();
	void SetPictureReflectivityEnabled(BOOL);
	short GetPictureReflectivityPerc();
	void SetPictureReflectivityPerc(short);
	short GetPictureReflectHeightPerc();
	void SetPictureReflectHeightPerc(short);
	long GetProgressBarType();
	void SetProgressBarType(long);
	long GetProgressBarMin();
	void SetProgressBarMin(long);
	long GetProgressBarMax();
	void SetProgressBarMax(long);
	long GetProgressBarValue();
	void SetProgressBarValue(long);
	unsigned long GetProgressBarColor();
	void SetProgressBarColor(unsigned long);
	long GetProgressBarFillMode();
	void SetProgressBarFillMode(long);
	unsigned long GetVistaColorGlowBottom();
	void SetVistaColorGlowBottom(unsigned long);
	unsigned long GetOffice2007ColorInnerBorder();
	void SetOffice2007ColorInnerBorder(unsigned long);
	unsigned long GetOffice2007ColorOuterBorder();
	void SetOffice2007ColorOuterBorder(unsigned long);
	unsigned long GetOffice2007ColorNorthTop();
	void SetOffice2007ColorNorthTop(unsigned long);
	unsigned long GetOffice2007ColorNorthBottom();
	void SetOffice2007ColorNorthBottom(unsigned long);
	unsigned long GetOffice2007ColorSouthTop();
	void SetOffice2007ColorSouthTop(unsigned long);
	unsigned long GetOffice2007ColorSouthBottom();
	void SetOffice2007ColorSouthBottom(unsigned long);
	unsigned long GetOffice2007ColorInnerBorderMouseOver();
	void SetOffice2007ColorInnerBorderMouseOver(unsigned long);
	unsigned long GetOffice2007ColorOuterBorderMouseOver();
	void SetOffice2007ColorOuterBorderMouseOver(unsigned long);
	unsigned long GetOffice2007ColorNorthTopMouseOver();
	void SetOffice2007ColorNorthTopMouseOver(unsigned long);
	unsigned long GetOffice2007ColorNorthBottomMouseOver();
	void SetOffice2007ColorNorthBottomMouseOver(unsigned long);
	unsigned long GetOffice2007ColorSouthTopMouseOver();
	void SetOffice2007ColorSouthTopMouseOver(unsigned long);
	unsigned long GetOffice2007ColorSouthBottomMouseOver();
	void SetOffice2007ColorSouthBottomMouseOver(unsigned long);
	unsigned long GetOffice2007ColorInnerBorderPressed();
	void SetOffice2007ColorInnerBorderPressed(unsigned long);
	unsigned long GetOffice2007ColorOuterBorderPressed();
	void SetOffice2007ColorOuterBorderPressed(unsigned long);
	unsigned long GetOffice2007ColorNorthTopPressed();
	void SetOffice2007ColorNorthTopPressed(unsigned long);
	unsigned long GetOffice2007ColorNorthBottomPressed();
	void SetOffice2007ColorNorthBottomPressed(unsigned long);
	unsigned long GetOffice2007ColorSouthTopPressed();
	void SetOffice2007ColorSouthTopPressed(unsigned long);
	unsigned long GetOffice2007ColorSouthBottomPressed();
	void SetOffice2007ColorSouthBottomPressed(unsigned long);
	unsigned long GetOffice2003ColorNorth();
	void SetOffice2003ColorNorth(unsigned long);
	unsigned long GetOffice2003ColorSouth();
	void SetOffice2003ColorSouth(unsigned long);
	unsigned long GetOffice2003ColorBorder();
	void SetOffice2003ColorBorder(unsigned long);
	unsigned long GetOffice2003ColorNorthMouseOver();
	void SetOffice2003ColorNorthMouseOver(unsigned long);
	unsigned long GetOffice2003ColorSouthMouseOver();
	void SetOffice2003ColorSouthMouseOver(unsigned long);
	unsigned long GetOffice2003ColorBorderMouseOver();
	void SetOffice2003ColorBorderMouseOver(unsigned long);
	unsigned long GetOffice2003ColorNorthPressed();
	void SetOffice2003ColorNorthPressed(unsigned long);
	unsigned long GetOffice2003ColorSouthPressed();
	void SetOffice2003ColorSouthPressed(unsigned long);
	unsigned long GetOffice2003ColorBorderPressed();
	void SetOffice2003ColorBorderPressed(unsigned long);
	BOOL GetToolTipEnabled();
	void SetToolTipEnabled(BOOL);
	CString GetToolTipTextNormal();
	void SetToolTipTextNormal(LPCTSTR);
	CString GetToolTipTextChecked();
	void SetToolTipTextChecked(LPCTSTR);
	short GetVistaOuterBorderWidth();
	void SetVistaOuterBorderWidth(short);
	short GetVistaMiddleBorderWidth();
	void SetVistaMiddleBorderWidth(short);
	short GetVistaInnerBorderWidth();
	void SetVistaInnerBorderWidth(short);
	short GetOffice2007OuterBorderWidth();
	void SetOffice2007OuterBorderWidth(short);
	short GetOffice2007InnerBorderWidth();
	void SetOffice2007InnerBorderWidth(short);
	short GetOffice2003BorderWidth();
	void SetOffice2003BorderWidth(short);
	CString GetSplitButtonPicture();
	void SetSplitButtonPicture(LPCTSTR);
	long GetSplitButtonType();
	void SetSplitButtonType(long);
	short GetSplitButtonArrowOffsetX();
	void SetSplitButtonArrowOffsetX(short);
	short GetSplitButtonArrowOffsetY();
	void SetSplitButtonArrowOffsetY(short);
	unsigned long GetSplitButtonArrowColor();
	void SetSplitButtonArrowColor(unsigned long);
	unsigned long GetSplitButtonHighlightColor();
	void SetSplitButtonHighlightColor(unsigned long);
	unsigned long GetSplitButtonShadowColor();
	void SetSplitButtonShadowColor(unsigned long);
	short GetSplitButtonSizePerc();
	void SetSplitButtonSizePerc(short);

// Operations
public:
	void EnableSound(short nSound, BOOL bEnable);
	void DoClick();
	void Refresh();
	void SetNSContainerColor(unsigned long Color);
	long SetPictureFromHandle(long index, long hBmp);
	long SetPictureFromMemory(long index, const VARIANT& pData, long sizeData);
	long SetAnimFromMemory(long index, const VARIANT& pData, long sizeData);
	long SetCursorFromHandle(long hCursor);
	long SetSoundFromMemory(long index, const VARIANT& pData, long sizeData);
	void SetAutomaticRefresh(BOOL bAutoRefresh);
	void SetSoundSync(long sound, BOOL flag);
	void EnableAcceleratorForVB();
	long SetPictureFromNet(long index, LPCTSTR strAddress, LPCTSTR strUsername, LPCTSTR strPassword);
	long SetSoundFromNet(long index, LPCTSTR strAddress, LPCTSTR strUsername, LPCTSTR strPassword);
	BOOL SetAnimFromNet(long index, LPCTSTR strAddress, LPCTSTR strUsername, LPCTSTR strPassword);
	void MouseCapture(BOOL bCapture);
	BOOL ExportBtnImage(long nImage, LPCTSTR strFilename, long nFormat);
	short LoadTemplate(LPCTSTR strFilename);
	short SaveTemplate(LPCTSTR strFilename);
	short LoadTemplateEx(LPCTSTR strFilename);
	short SaveTemplateEx(LPCTSTR strFilename);
	void SetHelpLink(short nPage, LPCTSTR strLink);
	void SetTemplateBinDir(long nType, LPCTSTR strDirPath);
	CString GetHelperString(short dispid, short nValue);
	void ResetProperties();
	short AnimGetFramesRate();
	long AnimSetFramesRate(short nRate);
	short AnimGetFramesCount();
	long AnimShowFrame(short nFrame);
	long AnimPause();
	long AnimResume();
	long AnimInvertPlay();
	void ClearButtonCache();
	short GetValueEx();
	void SetValueEx(short nValue);
	long GetButtonCacheSize();
	CString GetVersion();
	CString GetEdition();
	void SetTotalTransparentFactor(short nNewValue);
	void RefreshTransparentControl();
	void EnableButtonCache(BOOL bEnable);
	void SetCustomPaintFunction(long pFunction);
	void SetClipChildren(BOOL bSet);
	long GetControlBitmap(long nImage);
	void EnableDrawGdiPlus(BOOL bEnable);
	void SetFontPropertiesEx(long nTextPos, LPCTSTR strFacename, float nSize, BOOL bBold, BOOL bItalic, BOOL bUnderline, BOOL bStrikethrough);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BTNENH_H__6E214D69_FDC2_40CF_92B9_C53617DAC5C5__INCLUDED_)
