#if !defined(AFX_CELLSMANAGER_H__C1D86B9E_78D4_4DC0_B6E5_E54409964249__INCLUDED_)
#define AFX_CELLSMANAGER_H__C1D86B9E_78D4_4DC0_B6E5_E54409964249__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTextDescriptor;

/////////////////////////////////////////////////////////////////////////////
// CCellsManager wrapper class

class CCellsManager : public COleDispatchDriver
{
public:
	CCellsManager() {}		// Calls COleDispatchDriver default constructor
	CCellsManager(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCellsManager(const CCellsManager& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetScaleUnit();
	void SetScaleUnit(long);

// Operations
public:
	BOOL GetVisible(short nUniqueID);
	void SetVisible(short nUniqueID, BOOL bNewValue);
	CString GetText(short nUniqueID);
	void SetText(short nUniqueID, LPCTSTR lpszNewValue);
	CTextDescriptor GetTextDescriptor(short nUniqueID);
	void SetPictureNormal(short nUniqueID, LPCTSTR lpszNewValue);
	long GetTextHorzAlign(short nUniqueID);
	void SetTextHorzAlign(short nUniqueID, long nNewValue);
	long GetTextVertAlign(short nUniqueID);
	void SetTextVertAlign(short nUniqueID, long nNewValue);
	long GetPictureHorzAlign(short nUniqueID);
	void SetPictureHorzAlign(short nUniqueID, long nNewValue);
	long GetPictureVertAlign(short nUniqueID);
	void SetPictureVertAlign(short nUniqueID, long nNewValue);
	unsigned long GetBackColor(short nUniqueID);
	void SetBackColor(short nUniqueID, unsigned long newValue);
	unsigned long GetBorderColor(short nUniqueID);
	void SetBorderColor(short nUniqueID, unsigned long newValue);
	short GetBorderWidth(short nUniqueID);
	void SetBorderWidth(short nUniqueID, short nNewValue);
	void SetPictureDisabled(short nUniqueID, LPCTSTR lpszNewValue);
	short GetPictureTranspFactor(short nUniqueID);
	void SetPictureTranspFactor(short nUniqueID, short nNewValue);
	short GetBackTranspFactor(short nUniqueID);
	void SetBackTranspFactor(short nUniqueID, short nNewValue);
	BOOL CellAdd(short nUniqueID, float fPosLeft, float fPosTop, float fWidth, float fHeight, LPCTSTR strText);
	BOOL CellDelete(short nUniqueID);
	short CellGetCount();
	BOOL CellFind(short nUniqueID);
	BOOL CellGetLogFont(short nUniqueID, long pLogFont);
	BOOL CellSetLogFont(short nUniqueID, long pLogFont);
	short CellGetUniqueID(short nPosition);
	BOOL CellGetPos(short nUniqueID, float* pPosLeft, float* pPosTop);
	BOOL CellSetPos(short nUniqueID, float nPosLeft, float nPosTop);
	BOOL CellGetSize(short nUniqueID, float* pWidth, float* pHeight);
	BOOL CellSetSize(short nUniqueID, float nWidth, float nHeight);
	BOOL CellSetPictureFromHandle(short nUniqueID, long nPicture, long nHandle);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CELLSMANAGER_H__C1D86B9E_78D4_4DC0_B6E5_E54409964249__INCLUDED_)
